// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillCert.Infrastructure.Persistence;

#nullable disable

namespace SkillCert.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkillCertDbContext))]
    [Migration("20261005153433_AddTrainingRecords")]
    partial class AddTrainingRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_code");

                    b.HasKey("Id")
                        .HasName("pk_competencies");

                    b.HasIndex("NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("ix_competencies_normalized_code");

                    b.ToTable("competencies", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.CompetencyRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsPeerReview")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_peer_review");

                    b.Property<bool>("AllowsSelfReview")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_self_review");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("InvalidatesPreviousReviews")
                        .HasColumnType("boolean")
                        .HasColumnName("invalidates_previous_reviews");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int?>("RecertificationDays")
                        .HasColumnType("integer")
                        .HasColumnName("recertification_days");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("ShortTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("short_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_competency_revisions");

                    b.HasAlternateKey("Id", "CompetencyId")
                        .HasName("ak_competency_revision_id_competency_id");

                    b.HasIndex("CompetencyId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_competency_revisions_competency_id_revision_number");

                    b.ToTable("competency_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competency_revisions_recertification_days_positive", "recertification_days IS NULL OR recertification_days > 0");
                        });
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.RevisionPermittedClassification", b =>
                {
                    b.Property<Guid>("CompetencyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_revision_id");

                    b.Property<Guid>("ReviewerClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_classification_id");

                    b.HasKey("CompetencyRevisionId", "ReviewerClassificationId")
                        .HasName("pk_revision_permitted_classifications");

                    b.HasIndex("ReviewerClassificationId")
                        .HasDatabaseName("ix_revision_permitted_classifications_reviewer_classification_");

                    b.ToTable("revision_permitted_classifications", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.GroupListAssignment", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_id");

                    b.Property<Guid>("CompetencyListId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_list_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserGroupId", "CompetencyListId")
                        .HasName("pk_group_list_assignments");

                    b.HasIndex("CompetencyListId")
                        .HasDatabaseName("ix_group_list_assignments_competency_list_id");

                    b.ToTable("group_list_assignments", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_groups_name");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.UserGroupMembership", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("UserGroupId", "UserId")
                        .HasName("pk_user_group_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_group_memberships_user_id");

                    b.ToTable("user_group_memberships", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Lists.CompetencyList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_competency_lists");

                    b.ToTable("competency_lists", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Lists.CompetencyListNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<Guid>("CompetencyListId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_list_id");

                    b.Property<string>("HeadingCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("heading_code");

                    b.Property<string>("HeadingTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("heading_title");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("ParentKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Heading")
                        .HasColumnName("parent_kind");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_competency_list_nodes");

                    b.HasAlternateKey("Id", "CompetencyListId", "Kind")
                        .HasName("ak_competency_list_nodes_id_competency_list_id_kind");

                    b.HasIndex("CompetencyId")
                        .HasDatabaseName("ix_competency_list_nodes_competency_id");

                    b.HasIndex("CompetencyListId", "CompetencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_competency_list_nodes_competency_list_id_competency_id")
                        .HasFilter("competency_id IS NOT NULL");

                    b.HasIndex("CompetencyListId", "ParentNodeId", "SortOrder")
                        .HasDatabaseName("ix_competency_list_nodes_competency_list_id_parent_node_id_sor");

                    b.HasIndex("ParentNodeId", "CompetencyListId", "ParentKind")
                        .HasDatabaseName("ix_competency_list_nodes_parent_node_id_competency_list_id_par");

                    b.ToTable("competency_list_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_competency_list_nodes_parent_is_heading", "parent_kind = 'Heading'");

                            t.HasCheckConstraint("ck_competency_list_nodes_shape", "(kind = 'Heading' AND heading_title IS NOT NULL AND competency_id IS NULL) OR (kind = 'Competency' AND competency_id IS NOT NULL AND heading_title IS NULL AND heading_code IS NULL)");
                        });
                });

            modelBuilder.Entity("SkillCert.Domain.Records.ComplianceCheckpoint", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CompetencyListId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_list_id");

                    b.Property<DateTimeOffset?>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compliant");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.HasKey("UserId", "CompetencyListId")
                        .HasName("pk_compliance_checkpoints");

                    b.HasIndex("CompetencyListId")
                        .HasDatabaseName("ix_compliance_checkpoints_competency_list_id");

                    b.ToTable("compliance_checkpoints", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Records.TrainingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("blob_path");

                    b.Property<Guid>("CompetencyListId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_list_id");

                    b.Property<DateTimeOffset>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256hash")
                        .IsFixedLength();

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_training_records");

                    b.HasIndex("CompetencyListId")
                        .HasDatabaseName("ix_training_records_competency_list_id");

                    b.HasIndex("UserId", "GeneratedAt")
                        .HasDatabaseName("ix_training_records_user_id_generated_at");

                    b.HasIndex("UserId", "CompetencyListId", "CompletionDate")
                        .IsUnique()
                        .HasDatabaseName("ux_training_records_automatic")
                        .HasFilter("trigger = 'ComplianceAchieved'");

                    b.ToTable("training_records", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Reviewers.ReviewerClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffirmationPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("affirmation_policy");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_classifications");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_classifications_code");

                    b.ToTable("reviewer_classifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199a8c0-0000-7000-8000-000000000001"),
                            AffirmationPolicy = "Automatic",
                            Code = "Instructor",
                            Name = "Instructor",
                            Rank = 10
                        },
                        new
                        {
                            Id = new Guid("0199a8c0-0000-7000-8000-000000000002"),
                            AffirmationPolicy = "ReviewerConfirmation",
                            Code = "Supervisor",
                            Name = "Supervisor",
                            Rank = 20
                        });
                });

            modelBuilder.Entity("SkillCert.Domain.Reviews.CompetencyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_id");

                    b.Property<Guid>("CompetencyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competency_revision_id");

                    b.Property<string>("ConfirmationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confirmation_status");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReviewSignatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_signature_id");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_classification_id");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_name");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_user_id");

                    b.HasKey("Id")
                        .HasName("pk_competency_reviews");

                    b.HasIndex("CompetencyId")
                        .HasDatabaseName("ix_competency_reviews_competency_id");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("ix_competency_reviews_confirmed_by_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_competency_reviews_created_by_user_id");

                    b.HasIndex("RejectedByUserId")
                        .HasDatabaseName("ix_competency_reviews_rejected_by_user_id");

                    b.HasIndex("ReviewSignatureId")
                        .HasDatabaseName("ix_competency_reviews_review_signature_id");

                    b.HasIndex("ReviewerClassificationId")
                        .HasDatabaseName("ix_competency_reviews_reviewer_classification_id");

                    b.HasIndex("CompetencyRevisionId", "CompetencyId")
                        .HasDatabaseName("ix_competency_reviews_competency_revision_id_competency_id");

                    b.HasIndex("ReviewerUserId", "ReviewedAt")
                        .HasDatabaseName("ix_competency_reviews_pending_by_reviewer")
                        .HasFilter("confirmation_status = 'Pending'");

                    b.HasIndex("CandidateUserId", "CompetencyId", "ReviewedAt")
                        .HasDatabaseName("ix_competency_reviews_candidate_user_id_competency_id_reviewed");

                    b.ToTable("competency_reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_competency_reviews_confirmed_fields", "(confirmation_status = 'Confirmed') = (confirmed_at IS NOT NULL AND confirmed_by_user_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_competency_reviews_rejected_fields", "(confirmation_status = 'Rejected') = (rejected_at IS NOT NULL AND rejected_by_user_id IS NOT NULL AND rejection_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SkillCert.Domain.Reviews.ReviewSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_review_signatures");

                    b.ToTable("review_signatures", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_subject_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_administrator");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_subject_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SkillCert.Domain.Users.UserReviewerClassification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ReviewerClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_classification_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "ReviewerClassificationId")
                        .HasName("pk_user_reviewer_classifications");

                    b.HasIndex("ReviewerClassificationId")
                        .HasDatabaseName("ix_user_reviewer_classifications_reviewer_classification_id");

                    b.ToTable("user_reviewer_classifications", (string)null);
                });

            modelBuilder.Entity("SkillCert.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SkillCert.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SkillCert.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("SkillCert.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SkillCert.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.CompetencyRevision", b =>
                {
                    b.HasOne("SkillCert.Domain.Competencies.Competency", null)
                        .WithMany("Revisions")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_revisions_competencies_competency_id");

                    b.OwnsMany("SkillCert.Domain.Competencies.RevisionResource", "Resources", b1 =>
                        {
                            b1.Property<Guid>("CompetencyRevisionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("CompetencyRevisionId", "__synthesizedOrdinal");

                            b1.ToTable("competency_revisions");

                            b1
                                .ToJson("resources")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CompetencyRevisionId")
                                .HasConstraintName("fk_competency_revisions_competency_revisions_competency_revisio");
                        });

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.RevisionPermittedClassification", b =>
                {
                    b.HasOne("SkillCert.Domain.Competencies.CompetencyRevision", null)
                        .WithMany("PermittedClassifications")
                        .HasForeignKey("CompetencyRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revision_permitted_classifications_competency_revisions_com");

                    b.HasOne("SkillCert.Domain.Reviewers.ReviewerClassification", null)
                        .WithMany()
                        .HasForeignKey("ReviewerClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_revision_permitted_classifications_reviewer_classifications");
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.GroupListAssignment", b =>
                {
                    b.HasOne("SkillCert.Domain.Lists.CompetencyList", null)
                        .WithMany()
                        .HasForeignKey("CompetencyListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_list_assignments_competency_lists_competency_list_id");

                    b.HasOne("SkillCert.Domain.Groups.UserGroup", null)
                        .WithMany("AssignedLists")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_list_assignments_user_groups_user_group_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.UserGroupMembership", b =>
                {
                    b.HasOne("SkillCert.Domain.Groups.UserGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_memberships_user_groups_user_group_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_memberships_users_user_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Lists.CompetencyListNode", b =>
                {
                    b.HasOne("SkillCert.Domain.Competencies.Competency", null)
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_list_nodes_competencies_competency_id");

                    b.HasOne("SkillCert.Domain.Lists.CompetencyList", null)
                        .WithMany("Nodes")
                        .HasForeignKey("CompetencyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competency_list_nodes_competency_lists_competency_list_id");

                    b.HasOne("SkillCert.Domain.Lists.CompetencyListNode", null)
                        .WithMany()
                        .HasForeignKey("ParentNodeId", "CompetencyListId", "ParentKind")
                        .HasPrincipalKey("Id", "CompetencyListId", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_list_nodes_competency_list_nodes_parent_node_id_");
                });

            modelBuilder.Entity("SkillCert.Domain.Records.ComplianceCheckpoint", b =>
                {
                    b.HasOne("SkillCert.Domain.Lists.CompetencyList", null)
                        .WithMany()
                        .HasForeignKey("CompetencyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_checkpoints_competency_lists_competency_list_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compliance_checkpoints_domain_users_user_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Records.TrainingRecord", b =>
                {
                    b.HasOne("SkillCert.Domain.Lists.CompetencyList", null)
                        .WithMany()
                        .HasForeignKey("CompetencyListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_records_competency_lists_competency_list_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_records_domain_users_user_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Reviews.CompetencyReview", b =>
                {
                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_reviews_domain_users_candidate_user_id");

                    b.HasOne("SkillCert.Domain.Competencies.Competency", null)
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_reviews_competencies_competency_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_reviews_domain_users_confirmed_by_user_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_reviews_domain_users_created_by_user_id");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_reviews_domain_users_rejected_by_user_id");

                    b.HasOne("SkillCert.Domain.Reviews.ReviewSignature", null)
                        .WithMany()
                        .HasForeignKey("ReviewSignatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_reviews_review_signatures_review_signature_id");

                    b.HasOne("SkillCert.Domain.Reviewers.ReviewerClassification", null)
                        .WithMany()
                        .HasForeignKey("ReviewerClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competency_reviews_reviewer_classifications_reviewer_classi");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_reviews_domain_users_reviewer_user_id");

                    b.HasOne("SkillCert.Domain.Competencies.CompetencyRevision", null)
                        .WithMany()
                        .HasForeignKey("CompetencyRevisionId", "CompetencyId")
                        .HasPrincipalKey("Id", "CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_reviews_competency_revision_competency_revision_");
                });

            modelBuilder.Entity("SkillCert.Domain.Users.UserReviewerClassification", b =>
                {
                    b.HasOne("SkillCert.Domain.Reviewers.ReviewerClassification", null)
                        .WithMany()
                        .HasForeignKey("ReviewerClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_reviewer_classifications_reviewer_classifications_revi");

                    b.HasOne("SkillCert.Domain.Users.User", null)
                        .WithMany("Classifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_reviewer_classifications_users_user_id");
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.Competency", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("SkillCert.Domain.Competencies.CompetencyRevision", b =>
                {
                    b.Navigation("PermittedClassifications");
                });

            modelBuilder.Entity("SkillCert.Domain.Groups.UserGroup", b =>
                {
                    b.Navigation("AssignedLists");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("SkillCert.Domain.Lists.CompetencyList", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("SkillCert.Domain.Users.User", b =>
                {
                    b.Navigation("Classifications");
                });
#pragma warning restore 612, 618
        }
    }
}
