using System.Globalization;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace SkillCert.Infrastructure.Records;

/// <summary>
/// Renders a training record that reads like the paper AFA Skills Record (spec §21, development plan §2a): a dark
/// band per section, light bands for sub-sections, Date and Initials columns, and an evaluator legend at the end.
/// It never shows expiry dates, signatures, descriptions or resources.
/// </summary>
public static class TrainingRecordPdf
{
    // Design-system tokens (brand, brand-tint, ink, ink-muted, line).
    private const string Brand = "#a6192e";
    private const string BrandTint = "#f6dde1";
    private const string Ink = "#1f1a1b";
    private const string InkMuted = "#5d5456";
    private const string Line = "#857a7c";

    private static readonly CultureInfo English = CultureInfo.GetCultureInfo("en-CA");

    static TrainingRecordPdf()
    {
        // Free for organisations under the Community licence threshold; revisit for production.
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] Render(TrainingRecordModel model)
    {
        var initials = EvaluatorInitials.Assign(model.Rows.Select(r => r.EvaluatorName).OfType<string>());

        return Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.Letter);
            page.Margin(36);
            page.DefaultTextStyle(text => text.FontSize(9.5f).FontColor(Ink));

            page.Header().Element(header => Header(header, model));
            page.Content().PaddingTop(12).Column(column =>
            {
                column.Spacing(10);
                foreach (var section in Sections(model.Rows))
                {
                    // Start a section on a new page rather than leave its band stranded at the bottom.
                    column.Item().EnsureSpace(90).Element(item => SectionTable(item, section, initials));
                }

                if (initials.Count > 0)
                {
                    column.Item().PaddingTop(14).Element(item => Legend(item, initials));
                }
            });
            page.Footer().Row(row =>
            {
                row.RelativeItem().Text(text => text.Span($"Generated by SkillCert on {Format(model.GeneratedOn)}").FontSize(8).FontColor(InkMuted));
                row.AutoItem().Text(text =>
                {
                    text.DefaultTextStyle(style => style.FontSize(8).FontColor(InkMuted));
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        })).GeneratePdf();
    }

    /// <summary>Splits the rows at each top-level heading; rows before the first heading form their own section.</summary>
    private static List<List<TrainingRecordRow>> Sections(IReadOnlyList<TrainingRecordRow> rows)
    {
        var sections = new List<List<TrainingRecordRow>>();
        foreach (var row in rows)
        {
            if ((row.IsHeading && row.Depth == 0) || sections.Count == 0)
            {
                sections.Add([]);
            }

            sections[^1].Add(row);
        }

        return sections;
    }

    private static void Header(IContainer container, TrainingRecordModel model) => container.Column(column =>
    {
        column.Item().AlignCenter().Text(model.ListTitle).FontSize(18).Bold();
        column.Item().PaddingTop(8).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(90);
                columns.RelativeColumn(3);
                columns.ConstantColumn(96);
                columns.RelativeColumn(1.4f);
            });
            Label(table.Cell(), "Patroller name");
            Value(table.Cell(), model.CandidateName);
            Label(table.Cell(), "Completion date");
            Value(table.Cell(), model.CompletionDate is { } completed ? Format(completed) : "Not complete");
        });
    });

    private static void SectionTable(IContainer container, List<TrainingRecordRow> rows, IReadOnlyDictionary<string, string> initials) =>
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(48);
                columns.RelativeColumn();
                columns.ConstantColumn(72);
                columns.ConstantColumn(50);
            });

            foreach (var row in rows)
            {
                if (row.IsHeading && row.Depth == 0)
                {
                    Band(table, row, Brand, Colors.White, columnTitles: true);
                }
                else if (row.IsHeading)
                {
                    Band(table, row, BrandTint, Ink, columnTitles: false);
                }
                else
                {
                    Cell(table.Cell()).Text(row.Code ?? string.Empty);
                    Cell(table.Cell()).Text(row.Title);
                    Cell(table.Cell()).AlignCenter().Text(row.SignedOn is { } signed ? Format(signed) : string.Empty);
                    Cell(table.Cell()).AlignCenter().Text(row.SignedOn is not null && row.EvaluatorName is { } name ? initials[name] : string.Empty);
                }
            }
        });

    private static void Band(TableDescriptor table, TrainingRecordRow row, string background, string color, bool columnTitles)
    {
        IContainer Styled(IContainer cell) => cell.Border(0.75f).BorderColor(Line).Background(background).PaddingVertical(5).PaddingHorizontal(6);

        Styled(table.Cell()).Text(row.Code ?? string.Empty).FontColor(color).Bold();
        Styled(table.Cell()).Text(row.Title).FontColor(color).Bold();
        Styled(table.Cell()).AlignCenter().Text(columnTitles ? "Date" : string.Empty).FontColor(color).Bold();
        Styled(table.Cell()).AlignCenter().Text(columnTitles ? "Initials" : string.Empty).FontColor(color).Bold();
    }

    private static void Legend(IContainer container, IReadOnlyDictionary<string, string> initials) => container.Column(column =>
    {
        column.Item().PaddingBottom(4).Text("Evaluators").Bold();
        column.Item().Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(3);
                columns.ConstantColumn(56);
                columns.RelativeColumn(3);
                columns.ConstantColumn(56);
            });
            Label(table.Cell(), "Evaluator name");
            Label(table.Cell(), "Initials");
            Label(table.Cell(), "Evaluator name");
            Label(table.Cell(), "Initials");

            var entries = initials.ToList();
            for (var i = 0; i < entries.Count; i++)
            {
                Value(table.Cell(), entries[i].Key);
                Value(table.Cell(), entries[i].Value);
            }

            if (entries.Count % 2 == 1)
            {
                Value(table.Cell(), string.Empty);
                Value(table.Cell(), string.Empty);
            }
        });
    });

    private static IContainer Cell(IContainer cell) => cell.Border(0.75f).BorderColor(Line).PaddingVertical(4).PaddingHorizontal(6);

    private static void Label(IContainer cell, string text) => Cell(cell).Text(text).Bold();

    private static void Value(IContainer cell, string text) => Cell(cell).Text(text);

    private static string Format(DateOnly date) => date.ToString("d MMM yyyy", English);
}
